config/routes.rb
PaperlessIdocs::Application.routes.draw do
  resources :sections

end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :acronym, :name, :short_name, :position, :content, :parent_id
  has_ancestry
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sections }
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @section = Section.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.json
  def new
    @section = Section.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/1/edit
  def edit
    @section = Section.find(params[:id])
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render json: @section, status: :created, location: @section }
      else
        format.html { render action: "new" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.json
  def update
    @section = Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= t '.name'
    /[if lt IE 9]
      %script{ src: 'http://html5shim.googlecode.com/svn/trunk/html5.js', type: 'text/javascript' }

    = stylesheet_link_tag     'application', media: 'all'
    = javascript_include_tag  'application'
    = csrf_meta_tags
  %meta{ name:'viewport', content:'width=device-width, initial-scale=1.0' }

  .navbar.navbar-inverse.navbar-fixed-top
    .navbar-inner
      .container
        %a.btn.btn-navbar{ 'data-target' => '.nav-collapse', 'data-toggle' => 'collapse' }
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{ href: '#' }= t '.name'
        .nav-collapse
          %ul.nav
            - Section.roots.order(:position).each do |section|
              %li= link_to section.acronym, section, rel: 'tooltip', data: { title: section.name, placement: 'bottom' }

  .container
    - flash.each do |name, msg|
      .alert.fade.in{ class: "alert-#{ name == :notice ? 'success' : 'error'}" }
        %a.close{ 'data-dismiss' => 'alert' } ×
        = msg
    .row
      .span9
        = yield
      .span3
        = yield :sidebar

app/views/sections/_form.html.haml
= simple_form_for @section, html: {class: 'form-horizontal'} do |f|
  %fieldset
    %legend= "#{t("actions.#{controller.action_name.downcase}")} #{Section.model_name.human}"
    = f.input :name, input_html: { class: 'span5' }
    = f.input :acronym, input_html: { class: 'span2' }
    = f.input :parent_id, collection: Section.order(:name), input_html: { class: 'span5' }
    = f.input :position, input_html: { class: 'span1' }
    = f.input :content, input_html: { class: 'span7', rows: '8' }

    .form-actions
      = f.button :submit, class: 'btn-primary'
      = link_to t('actions.cancel'), sections_path, class: 'btn'

app/views/sections/_section_links.html.haml
%ul
  - sections.each do |section, children|
    %li= link_to_unless_current section.name, section
    = render 'section_links', sections: children if children.present?

app/views/sections/edit.html.haml
= render 'form'

app/views/sections/index.html.haml
%h1 Listing sections

%table.table.table-striped
  %thead
    %tr
      %th= Section.human_attribute_name :name
      %th= Section.human_attribute_name :acronym
      %th= Section.human_attribute_name :parent
      %th= Section.human_attribute_name :position
      %th= t 'actions.actions'
  %tbody
    - @sections.each do |section|
      %tr
        %td= link_to section.name, section, rel: 'tooltip', title: t('actions.show')
        %td= section.acronym
        %td= section.parent.try(:acronym)
        %td= section.position
        %td
          = link_to t('actions.edit'), edit_section_path(section), class: 'btn btn-mini'
          = link_to t('actions.destroy'), section, confirm: t('actions.confirm'), method: :delete, class: 'btn btn-mini btn-danger'

= link_to "#{t('actions.new')} #{Section.model_name.human}", new_section_path, class: 'btn btn-primary'

app/views/sections/new.html.haml
= render 'form'

app/views/sections/show.html.haml
// TODO: 
//   1. Collapse li's
//   2. Move to partial?
=content_for :sidebar do
  %h3= t 'sidebar.table_of_contents'
  = render 'section_links', sections: @section.root.descendants.arrange(order: :position)

// TODO:
//   1. Move to partial
- unless @section.is_root?
  %ul.breadcrumb
    - @section.ancestors.each do |section|
      %li
        = link_to section.name, section
        %span.divider &gt;

// TODO:
//   1. Format header according to depth of node
//   2. Display Markdown
%p
  %h2= @section.name
%p
  = simple_format @section.content

// TODO:
//   1. Display link to next / previous page
//     a. flatten arranged, ordered root descendants
//     b. find this @section.id
//     c. link to previous/next section
//   2. Extract to helper
//   3. Move to partial
%ul.pager
  %li= link_to 'Previous', '#'
  %li= link_to 'Next', '#'

// TODO:
//   1. Make 'New section before', 'New section after' and 'New child' buttons
//     a. 'New child' only of it does not have childs
//   2. Prevent deletion of sections with childs (remove button)
//   3. Authorize actions with roles
.form-actions
  = link_to t('actions.back'), sections_path, class: 'btn'
  = link_to t('actions.edit'), edit_section_path(@section), class: 'btn'
  = link_to t('actions.destroy'), @section, confirm: t('actions.confirm'), method: :delete, class: 'btn btn-danger'